version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fewo-willrich-build
    ports:
      - 4200:4200
    volumes:
      - ./fewo-willrich:/usr/fewo-willrich
    container_name: fewo-willrich-build
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: npm start
    networks:
      - fewo-willrich-nw

networks:
  fewo-willrich-nw:
